### ISSUE TITLE
Saving to `obj` bug

### ISSUE THREAD

**Issue by FedeClaudi** [marcomusy/vedo#161] opened 2020-06-15 10:50 UTC
Hi Marco, 

I'm testing the latest version of `vedo` but I get an error when saving to `.obj`:
Has to do with this line: https://github.com/marcomusy/vedo/blob/01e9c42ce910974d33f29ddba2d46bc1e6823812/vedo/vtkio.py#L1138

The error:
```
>           for l in objct.lines(joined=True):
E           TypeError: lines() got an unexpected keyword argument 'joined'

../../../miniconda3/envs/brtest/lib/python3.7/site-packages/vedo/vtkio.py:1138: TypeError
```

I've tried updating `vtk` to the latest version but that didn't help. Is there anything else I should update?

**Comment by marcomusy** [comment] 2020-06-15 11:16
..I forgot to eliminate the `joined` kw :(
should be fixed in the master with the usual
`pip install -U git+https://github.com/marcomusy/vedo.git`

**Comment by FedeClaudi** [comment] 2020-06-15 11:19
thanks for looking into it so quickly, it works now. 

Is there any chance you can release a fixed version on pypi? I'll soon enough release a new version of brainrender and would need this.

**Comment by marcomusy** [comment] 2020-06-15 11:23
I could make a minor release not before tomorrow evening or wed morning

**Comment by FedeClaudi** [comment] 2020-06-15 11:28
that's perfect, thank you :)

**Comment by FedeClaudi** [comment] 2020-06-18 08:28
Thanks for the release, it works perfectly!

-----

By the way, completely unrelated question, do you have idea why the VTK widget for pyqt5 applications gives low resolution renderings on mac compared to windows??

**Comment by marcomusy** [comment] 2020-06-18 10:12
> By the way, completely unrelated question, do you have idea why the VTK widget for pyqt5 applications gives low resolution renderings on mac compared to windows??

I'm not sure... it may be caused by the way the operative system takes control of the antialiasing of an application. I dont know if vtk is responsible for that, i guess it's a graphics driver related thing..

**Comment by FedeClaudi** [comment] 2020-06-18 10:13
I see, okay. Thanks Marco :)

**Closed** 2020-06-18 10:22 UTC
Labels: bug
